FROM openjdk:8-jre-slim

ENV SPRING_PROFILES_ACTIVE "${SPRING_PROFILES_ACTIVE:-cloud,default,docker}"

EXPOSE 8080

COPY ./target/easyrmt-0.8.0.jar /

ENTRYPOINT java -jar /easyrmt-0.8.0.jar \
--spring.profiles.active="${SPRING_PROFILES_ACTIVE}"
