FROM openjdk:8-jre-slim

ENV SPRING_PROFILES_ACTIVE "${SPRING_PROFILES_ACTIVE:-cloud,default,docker}"

EXPOSE ${TCP_PORTS}

COPY "target/EasyRMT@project.version@.jar" /

ENTRYPOINT java -jar "/EasyRMT@project.version@.jar" \
--spring.profiles.active="${SPRING_PROFILES_ACTIVE}"
