version: '3.1'

services:

  db:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: easyRMT
      MYSQL_DATABASE: easyrmt

    ports:
      - 3308:3306

  app:
      build:
        context: ./src/main/java/com/Sergio
        dockerfile: target/docker/dockerfile
      image: EasyRMT
      depends_on:
        - db
      ports:
        - 8650:80
      environment:
        - TCP_PORTS=80